"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const networkController_1 = __importDefault(require("../controllers/networkController"));
const networkRouter = (0, express_1.Router)();
networkRouter.post('/details/address', networkController_1.default.getAddressDetailsAPI);
networkRouter.post('/details/address/transaction_history', networkController_1.default.getAddressTransactionHistoryAPI);
networkRouter.post('/details/address/token_transfers', networkController_1.default.getTokenTransfersAPI);
networkRouter.post('/details/address/nfts', networkController_1.default.getAddressNFTsAPI);
networkRouter.post('/details/address/balance', networkController_1.default.getAddressTokenBalancesAPI);
networkRouter.post('/search/hash', networkController_1.default.searchByHashAPI);
networkRouter.post('/details/contract', networkController_1.default.getSmartContractDetailsAPI);
networkRouter.post('/token/info', networkController_1.default.getTokenInfoAPI);
networkRouter.post('/token/holders', networkController_1.default.getTokenHoldersAPI);
networkRouter.post('/contract/nft', networkController_1.default.getContractNFTsAPI);
networkRouter.post('/token/transfers', networkController_1.default.getTokenTransfersAPI);
networkRouter.post('/stats', networkController_1.default.getStatsAPI);
networkRouter.post('/stats/charts/transactions', networkController_1.default.getStatsTransactionsAPI);
networkRouter.post('/main-page/blocks', networkController_1.default.getLatestBlocksAPI);
networkRouter.post('/main-page/transactions', networkController_1.default.getLatestTransactionsAPI);
exports.default = networkRouter;
